[[main]]
  name = "Quantum"
  pageRef = "Quantum"
  weight = 1

[[main]]
  name = "AI/ML"
  pageRef = "AI-ML"
  weight = 2

[[main]]
  name = "Rust"
  pageRef = "Rust"
  weight = 3

[[main]]
  name = "GoLang"
  pageRef = "GoLang"
  weight = 4

[[footer]]
none = "none"
